In [ ]:
import pandas as pd
from datasets import load_dataset
dataset = load_dataset('lukebarousse/data_jobs')


df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/3.25k [00:00<?, ?B/s]

data_jobs.csv: reconstructing file:   0%|          |  0.00B /  231MB

data_jobs.csv: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

In [ ]:
df.describe()

                     job_posted_date  salary_year_avg  salary_hour_avg
count                         785741     22003.000000     10662.000000
mean   2023-06-25 16:02:11.860248576    123286.274072        47.016598
min              2023-01-01 00:00:04     15000.000000         8.000000
25%              2023-03-20 10:05:48     90000.000000        27.500000
50%              2023-06-29 06:11:38    115000.000000        45.980000
75%              2023-09-27 01:01:16    150000.000000        61.159996
max              2023-12-31 23:59:58    960000.000000       391.000000
std                              NaN     48312.449482        21.890738

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [ ]:
df['salary_year_avg'].mean()

np.float64(123286.27407182401)

In [ ]:
df['salary_year_avg'].min()

15000.0

In [ ]:
minimum_salary = df['salary_year_avg'].idxmin()

In [ ]:
df.iloc[minimum_salary]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
Name: 665729, dtype: object

In [ ]:
df['job_title_short'].value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

In [ ]:
df.groupby('job_title_short')[['salary_year_avg', 'salary_hour_avg']].agg(['min', 'max', 'median'])

                          salary_year_avg                     salary_hour_avg  \
                                      min       max    median             min
job_title_short
Business Analyst                  16500.0  387460.0   85000.0          10.835
Cloud Engineer                    42000.0  280000.0   90000.0          18.500
Data Analyst                      25000.0  650000.0   90000.0           8.000
Data Engineer                     15000.0  525000.0  125000.0           8.000
Data Scientist                    27000.0  960000.0  127500.0           8.000
Machine Learning Engineer         30000.0  325000.0  106415.0          10.000
Senior Data Analyst               30000.0  425000.0  111175.0          13.000
Senior Data Engineer              35000.0  425000.0  147500.0          12.500
Senior Data Scientist             45000.0  890000.0  155500.0          17.500
Software Engineer                 28000.0  375000.0   99150.0          11.000


                             max     median
job_title_short
Business Analyst           132.5  40.362499
Cloud Engineer              91.0  40.000000
Data Analyst               391.0  32.615002
Data Engineer              184.5  58.500000
Data Scientist             237.5  47.500000
Machine Learning Engineer   87.5  47.535000
Senior Data Analyst        130.0  47.500000
Senior Data Engineer       170.0  61.500000
Senior Data Scientist      150.0  47.620003
Software Engineer          102.5  47.560001