In [ ]:
!pip install -q datasets

import pandas as pd
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Clean up
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/3.25k [00:00<?, ?B/s]

data_jobs.csv: reconstructing file:   0%|          |  0.00B /  231MB

data_jobs.csv: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

In [ ]:
df['job_country'].value_counts().head(20)

job_country
United States     206292
India              51088
United Kingdom     40375
France             39922
Germany            27694
Spain              25100
Singapore          23696
Sudan              21781
Netherlands        20631
Italy              17013
Canada             16029
Mexico             15139
Poland             14793
Portugal           14508
Australia          12955
South Africa       12414
Belgium            12078
Philippines        11786
Ireland            11162
Switzerland         9924
Name: count, dtype: int64

In [ ]:
us_jobs = df[df['job_country'] == 'United States']

In [ ]:
us_jobs = us_jobs[us_jobs['salary_year_avg'].notna()]

In [ ]:
us_jobs.groupby('job_title_short')['salary_year_avg'].agg(['min', 'median', 'max', 'count']).sort_values(by='median', ascending=False)

                               min    median       max  count
job_title_short
Senior Data Scientist      55000.0  155000.0  475000.0   1241
Machine Learning Engineer  44408.5  150000.0  315000.0    128
Senior Data Engineer       45000.0  150000.0  375000.0   1058
Data Scientist             30000.0  130000.0  960000.0   4553
Software Engineer          48982.0  130000.0  375000.0    157
Data Engineer              23496.0  125000.0  525000.0   2915
Cloud Engineer             42000.0  116100.0  221844.0     20
Senior Data Analyst        35360.0  110000.0  425000.0    913
Business Analyst           35000.0   90000.0  387460.0    431
Data Analyst               25000.0   90000.0  375000.0   4350

# Problems

In [ ]:
df['salary_year_avg'].mean()

np.float64(123286.27407182401)

In [ ]:
df.salary_year_avg.median()

115000.0

In [ ]:
df.groupby('job_title_short')['salary_hour_avg'].mean()

job_title_short
Business Analyst             42.723415
Cloud Engineer               45.560715
Data Analyst                 38.106918
Data Engineer                57.196998
Data Scientist               49.361403
Machine Learning Engineer    48.477935
Senior Data Analyst          47.661218
Senior Data Engineer         62.848496
Senior Data Scientist        54.105631
Software Engineer            46.452019
Name: salary_hour_avg, dtype: float64

In [ ]:
df.iloc[df['salary_hour_avg'].idxmin()]

job_title_short                                             Data Scientist
job_title                   Data Scientist | W2 Only |Remote then CLT/ ATL
job_location                                                North Carolina
job_via                                                           via Dice
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                    New York, United States
job_posted_date                                        2023-01-20 00:20:23
job_no_degree_mention                                                False
job_health_insurance                                                 False
job_country                                                  United States
salary_rate                                                           hour
salary_year_avg                                                        NaN
salary_hour_avg                                                        8.0
company_name                                                 Matlen Silver
job_skills               ['python', 'oracle', 'pandas', 'numpy', 'tenso...
job_type_skills          {'analyst_tools': ['word', 'tableau'], 'cloud'...
Name: 88185, dtype: object

In [ ]:
job_count_by_country = df.groupby('job_country').size()
job_count_by_country

job_country
Afghanistan      16
Albania         119
Algeria         111
Angola           11
Argentina      8736
               ...
Venezuela        69
Vietnam        2414
Yemen            10
Zambia          104
Zimbabwe         81
Length: 160, dtype: int64

In [ ]:
job_count_kenya = df.groupby('job_country')['salary_year_avg'].max()
print(job_count_kenya['Kenya'])

147500.0